provider:
  name: openfaas

functions:
  app:
    lang: golang-http-handler
    engine: cloud
    namespace: freeloot
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/backend-config: '{"default": "web"}'
    replicas: 1